# Generated by Django 3.2.11 on 2022-01-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calender_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('emotion', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'CALENDAR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=7, null=True)),
                ('contact', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.calendar')),
                ('sentence', models.TextField()),
                ('voice', models.TextField()),
                ('enjoyment', models.FloatField()),
                ('sadness', models.FloatField()),
                ('anger', models.FloatField()),
                ('surprise', models.FloatField()),
                ('disgust', models.FloatField()),
                ('fear', models.FloatField()),
            ],
            options={
                'db_table': 'DETAIL',
                'managed': False,
            },
        ),
    ]
